### ISSUE TITLE
Update Packal

### ISSUE THREAD

**Issue by counterbeing** [deanishe/alfred-network-location#3]
The current version available at packal.org appears to be 1.0.
http://www.packal.org/workflow/network-location

I realize this isn't a code change exactly :)

**Comment by deanishe** [comment]
Packal's operator walked away a few years ago, and it's an unmaintained zombie now. I don't upload workflows to it any more because it doesn't work most of the time.

**Comment by counterbeing** [comment]
I came to that conclusion a little while after submitting this issue. It’s a shame. The Alfred community would really benefit from a package manager.

**Comment by deanishe** [comment]
> The Alfred community would really benefit from a package manager.

Well, a decent workflow index/search engine. Many, if not all, workflows can update themselves. The main problem is discovery.

**Comment by counterbeing** [comment]
Well thanks for getting back to me :)
