### ISSUE TITLE
Would it possible to get a "Monterey 12.3" python2 fix for this workflow?

### ISSUE THREAD

**Issue by joeynotjoe** [deanishe/alfred-network-location#6]
If anyone has the knowledge and time to update this workflow to be compatible with Monterey 12.3, I would really appreciate it! I'm thinking it is the removal of python2 that is causing trouble.

**Comment by karkraeg** [comment]
Try `which python` in your Terminal and change the Python path like this:
![Screenshot_2022-07-03_194007@2x](https://user-images.githubusercontent.com/8436596/177051202-ca5440a6-db73-45a0-8291-7697b6009f55.png)

That worked for me.

**Comment by joeynotjoe** [comment]
I ended up adding this at the top of the script and it seems to have worked as well. But I've also done some of hte other python2 related workarounds so I'm not fully sure where the fix came from.
![VRQ651Z](https://user-images.githubusercontent.com/10430495/178114359-ab739f85-8075-4a57-be75-03c38fb4aa11.png)
